### ISSUE TITLE
node js support

### ISSUE THREAD

**Issue by RebeccaStevens** [gqgs/upscalejs#1]
It seems that currently this lib doesn't support node js. Could support be added?

I would assume a common use case for this would be to upscale images as part of a build process.

**Comment by gqgs** [comment]
Hi @RebeccaStevens. I don't see any immediate reasons why it wouldn't be possible.
Our main dependency is onnxruntime and apparently it does already have [node support](https://www.npmjs.com/package/onnxruntime-node).

I'll play around with it and see if we can support it here as well.

**Comment by gqgs** [comment]
@RebeccaStevens Done in 1abb1100dedfda89b376fe4c71e04abe871f40fc. You can find an example on how to use it in the README.

Notice that for now everything is done sequentially for Node so the worker options that you can pass to the constructor will be silently ignored.
A follow-up would be to use `worker_threads` to support those options and process tiles in parallel some day.
